apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-go
  template:
    metadata:
      labels:
        app: nginx-go
    spec:
      containers:
        - name: nginx
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80

          volumeMounts:
            - name: nginx-conf
#              subPath: nginx.conf
              mountPath: /etc/nginx/conf.d
              readOnly: true

      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
