apiVersion: v1
kind: Service
metadata:
  name: app-go-nginx
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30080
  selector:
    app: app-go

---
apiVersion: v1
kind: Service
metadata:
  name: app-go
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: app-go